# ── Redirect HTTP → HTTPS ──────────────────────────────────
server {
    listen 80;
    server_name proshop-team-master-devops.duckdns.org;
    return 301 https://$host$request_uri;
}

# ── HTTPS Server ───────────────────────────────────────────
server {
    listen 443 ssl;
    server_name proshop-team-master-devops.duckdns.org;

    # Chứng chỉ SSL (mount từ host vào container)
    ssl_certificate     /etc/letsencrypt/live/proshop-team-master-devops.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/proshop-team-master-devops.duckdns.org/privkey.pem;

    # Bảo mật SSL
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root  /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass         http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        proxy_pass       http://backend:5000;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}